### ISSUE TITLE
ゲーム本体と公式サイトでヒーローのステータスが違う

### ISSUE THREAD

**Issue by mitsuru793** [matthew70/vainglory#14]
スカーフの初期ステータスはHPが632で、1レベルごとに65アップすると下記サイトには書かれています。計算すると`632 + 65 * 11 = 1347`となります。
しかし、ゲーム本体のヒーロー情報を見ると、初期値は合っていますが、最大レベル時のHPは1490とあります。テストコードにこの値を使用して気づきました。

また、スカイの情報はサイトには乗っていないので、glowを計算するかなり細かい少数になる項目値がありました。
`例： 武器ダメージ:5.90909091`
もしかしたら、サイトに載せているのは小数点以下切り捨ての成長値がかもしれません。

*\* スカーフのステータス **
- [英語版公式サイト](http://www.vainglorygame.com/heroes/skaarf/)
- [日本語版公式サイト](http://jp.vainglorygame.com/heroes/skaarf/)
- [vaingloryfire](http://www.vaingloryfire.com/vainglory/wiki/heroes/skaarf)

**Comment by Imfloppy** [comment]
なんと！
返事来るかわかりませんが、公式ツイッターに聞いてみました:+1:

> また、スカイの情報はサイトには乗っていないので、glowを計算するかなり細かい少数になる項目値がありました。

ふむふむ

**Comment by mitsuru793** [comment]
ペタルのHPも違いました。
ゲーム本体だと1346、計算すると1347でした。

**Comment by Imfloppy** [comment]
スカーフはゲーム本体の1490が正しいとのことです！

近日中にWebの表記を直してくれるとは思いますが、とりあえずはアプリとvaingloryfireを参考にすると良さそうですかね。

## 

https://twitter.com/matthew70_/status/642583945779871744

**Comment by mitsuru793** [comment]
とうことはステータスは初期値に成長値を足していく計算で合っているのですね。
SKYEだけ成長値が凄い細かいのか。これはかなりの調整をしたという理由かもしれません。

ご確認ありがとうございます。

**Comment by Imfloppy** [comment]
いったんクローズしておきます:bow:
